//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CES
{


    public partial class AdminLogin
    {
        protected global::System.Web.UI.WebControls.TextBox txtuser;
        protected global::System.Web.UI.WebControls.TextBox txtpass;
        protected global::System.Web.UI.WebControls.Button btnlogin;
    }
}
